CREATE TABLE items (
`id` INT(11) NOT NULL AUTO_INCREMENT,
`name` VARCHAR(128),
`description` VARCHAR(128),
`location` VARCHAR(128),
`surrendered_by` VARCHAR(255),
`active` INT(11) NOT NULL DEFAULT '0',
`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET= latin1 AUTO_INCREMENT=1;
